apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
data:
  PORT: "8080"
  AWS_REGION: "us-east-1"
  PRODUCT_IMAGES_BUCKET: "gym-platform-product-images"
  AUTH_SERVICE_URL: "http://auth-service:4000"
  OPERATIONS_SERVICE_URL: "http://operations-service:4001"
  PEOPLE_SERVICE_URL: "http://people-service:4002"
  SOCIAL_SERVICE_URL: "http://social-service:4003"
  ORDER_SERVICE_URL: "http://order-service:4004"
  PAYMENT_SERVICE_URL: "http://payment-service:4005"
  COMMERCE_SERVICE_URL: "http://commerce-service:4006"
  AI_SERVICE_URL: "http://ai-service:4007"
