apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip

    # Connect to your ClusterIssuer
    cert-manager.io/cluster-issuer: letsencrypt-duckdns

    # Open HTTP (80) & HTTPS (443) listeners
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 80}, {"HTTPS": 443}]'

    # Redirect all HTTP requests to HTTPS automatically
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  tls:
    - hosts:
        - iti-gym-platform.duckdns.org
      secretName: api-gateway-tls     # cert-manager will auto-create this secret
  rules:
    - host: gym-platform.duckdns.org
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080