apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: progress-mongo-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: progress-mongo-credentials
    creationPolicy: Owner
  data:
    - secretKey: MONGO_INITDB_ROOT_USERNAME
      remoteRef:
        key: gym/dev/progress-mongo-credentials
        property: username
    - secretKey: MONGO_INITDB_ROOT_PASSWORD
      remoteRef:
        key: gym/dev/progress-mongo-credentials
        property: password
