apiVersion: v1
kind: Service
metadata:
  name: gym-progress-service
  labels:
    app: gym-progress-service
spec:
  type: ClusterIP
  selector:
    app: gym-progress-service
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
