apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: gym-dev

# argocd-image-updater fills in newName/newTag under this entry.
images:
  - name: gym-profile-service

patches:
  - path: patch-deployment.yaml
