apiVersion: v1
kind: ConfigMap
metadata:
  name: operations-service-config
data:
  PORT: "4001"
  DB_HOST: "operations-postgres"
  DB_PORT: "5432"
  DB_NAME: "gym_operations_db"
  REDIS_URL: "redis://operations-redis:6379"
  KAFKA_BROKERS: "kafka:9092"
  KAFKAJS_NO_PARTITIONER_WARNING: "1"
  PAYMENT_SERVICE_URL: "http://payment-service:4005"