apiVersion: apps/v1
kind: Deployment
metadata:
  name: operations-redis
  labels:
    app: operations-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operations-redis
  template:
    metadata:
      labels:
        app: operations-redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          ports:
            - containerPort: 6379
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 3
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 10