apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-svc-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: auth-svc-credentials  
    creationPolicy: Owner              
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: gym/dev/auth-db-credentials
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: gym/dev/auth-db-credentials
        property: password
    - secretKey: JWT_SECRET
      remoteRef:
        key: gym/dev/auth-service/jwt