apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: social-svc-credentials
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: ClusterSecretStore
  target:
    name: social-svc-credentials
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_USER
      remoteRef:
        key: gym/dev/social-db-credentials
        property: username
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: gym/dev/social-db-credentials
        property: password
