apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: social-postgres
spec:
  serviceName: social-postgres
  replicas: 1
  selector:
    matchLabels:
      app: social-postgres
  template:
    metadata:
      labels:
        app: social-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef: { name: social-svc-credentials, key: POSTGRES_USER }
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef: { name: social-svc-credentials, key: POSTGRES_PASSWORD }
            - name: POSTGRES_DB
              value: "gym_social"
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          readinessProbe:
            exec:
              command: ["pg_isready", "-h", "127.0.0.1", "-p", "5432"]
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            exec:
              command: ["pg_isready", "-h", "127.0.0.1", "-p", "5432"]
            initialDelaySeconds: 10
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
        storageClassName: gp3
