apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: api-gateway-prod
  namespace: argocd
spec:
  project: gym-platform
  source:
    repoURL: https://github.com/HyperScale-Fitness-Platform/gym-platform-gitops.git
    targetRevision: main
    path: services/api-gateway/overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: gym-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: false