apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gym-platform-root-dev
  namespace: argocd
spec:
  project: gym-platform
  source:
    repoURL: https://github.com/HyperScale-Fitness-Platform/gym-platform-gitops.git
    targetRevision: main
    path: services
    directory:
      recurse: true
      include: "application-dev.yaml" # <-- Only deploys child dev Application CRDs
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true