apiVersion: v1
kind: Service
metadata:
  name: gym-profile-service
  labels:
    app: gym-profile-service
spec:
  type: ClusterIP
  selector:
    app: gym-profile-service
  ports:
    - port: 4002
      targetPort: 4002
      protocol: TCP
      name: http
