apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: gym-platform-updater
  namespace: argocd
spec:
  writeBackConfig:
    method: git
    gitConfig:
      branch: main
  applicationRefs:
    - namePattern: "auth-service-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/auth-service/overlays/${ENVIRONMENT}"
      images:
        - alias: authsvc
          imageName: "${ECR_REGISTRY}/gym-auth-service"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "gym-auth-service"
    - namePattern: "api-gateway-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/api-gateway/overlays/${ENVIRONMENT}"
      images:
        - alias: apisvc
          imageName: "${ECR_REGISTRY}/gym-api-gateway"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "gym-api-gateway"
    - namePattern: "profile-service-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/profile-service/overlays/${ENVIRONMENT}"
      images:
        - alias: profilesvc
          imageName: "${ECR_REGISTRY}/gym-profile-service"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "gym-profile-service"
    - namePattern: "social-service-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/social-service/overlays/${ENVIRONMENT}"
      images:
        - alias: socialsvc
          imageName: "${ECR_REGISTRY}/gym-social-service"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "gym-social-service"
    - namePattern: "ai-service-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/ai-service/overlays/${ENVIRONMENT}"
      images:
        - alias:aisisvc
          imageName: "${ECR_REGISTRY}/gym-ai-service"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "gym-ai-service"
    - namePattern: "frontend-service-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/frontend-service/overlays/${ENVIRONMENT}"
      images:
        - alias: frontendsvc
          imageName: "${ECR_REGISTRY}/frontend-service"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "frontend-service"
    - namePattern: "progress-service-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/progress-service/overlays/${ENVIRONMENT}"
      images:
        - alias: progresssvc
          imageName: "${ECR_REGISTRY}/gym-progress-service"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "gym-progress-service"
    - namePattern: "operations-service-${ENVIRONMENT}"
      writeBackConfig:
        gitConfig:
          writeBackTarget: "kustomization:./services/operations-service/overlays/${ENVIRONMENT}"
      images:
        - alias: operationssvc
          imageName: "${ECR_REGISTRY}/gym-operations-service"
          commonUpdateSettings:
            updateStrategy: newest-build
          manifestTargets:
            kustomize:
              name: "gym-operations-service"
