apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: gym-order-postgres
  labels:
    app: gym-order-postgres
    component: database
spec:
  serviceName: gym-order-postgres
  replicas: 1
  selector:
    matchLabels:
      app: gym-order-postgres
      component: database
  template:
    metadata:
      labels:
        app: gym-order-postgres
        component: database
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
              name: postgres
          envFrom:
            - secretRef:
                name: order-svc-credentials
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "$(POSTGRES_USER)"]
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: gym-order-postgres
          component: database
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: gp3
        resources:
          requests:
            storage: 10Gi
