apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gym-dev

resources:
  - configmap.yaml
  - pvc.yaml
  - service.yaml
  - deployment.yaml
  - kafka-ui/deployment.yaml
  - kafka-ui/service.yaml
  - kafka-ui/ingress.yaml
